twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    strict_variables: false
    cache: true
    form_themes: ['form/flowbite-layout.html.twig']
    globals:
        appVersion: '@App\Application\AppVersion'
        appConfig: '@App\Infrastructure\Config\AppConfig'
        enrichedActivities: '@App\Domain\Activity\EnrichedActivities'
        bestEffortsCalculator: '@App\Domain\Activity\BestEffort\BestEffortsCalculator'
        FilterName: 'App\Infrastructure\Twig\Filters\FilterName'
