twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    strict_variables: false
    cache: true
    form_themes: ['form/flowbite-layout.html.twig']
    globals:
        appVersion: '@App\BuildApp\AppVersion'
