general:
  app_url: 'http://localhost:8080/'
  profile_picture_url: null
  appSubTitle: 'Robin The King ðŸ‘‘'
  ntfy_url: null
  athlete:
    birthday: '1989-08-14'
    max_heart_rate_formula: 'fox'
    weight_history:
      "2020-01-01": 68
    ftp_history:
      "2023-01-01": 198
      "2023-03-22": 220
      "2023-03-29": 238
      "2023-04-01": 250
appearance:
  locale: 'en_US'
  unit_system: 'metric'
  time_format: 24
  date_format: 'DAY-MONTH-YEAR'
import:
  number_of_new_activities_to_process_per_import: 250
  sport_types_to_import: []
  activity_visibilities_to_import: []
  skip_activities_recorded_before: null
  activitiesToSkipDuringImport: ['skip']
  optInToSegmentDetailImport: true
gear:
  customGear:
    enabled: true
    hashtagPrefix: sfs
    customGears:
      - tag: peddle-board
        label: Peddle Board
        isRetired: false
        purchasePrice:
          amountInCents: 123456
          currency: 'EUR'
      - tag: workout-shoes
        label: Fancy workout shoes
        isRetired: true
zwift:
  level: 80
  racing_score: 495
