name: ci
on:
  workflow_dispatch:
  pull_request:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
permissions:
  pull-requests: write
jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug

      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v5

      - name: Copy .env file
        run: cp .env.test .env

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Validate composer.json
        run: composer validate --strict

      - name: Validate PSR-4 compliance
        run: composer dump-autoload --dev --optimize --strict-psr

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse

      - name: Run Rector
        run: vendor/bin/rector --dry-run

      - name: Run PHPcs fixer dry-run
        run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation --config=.php-cs-fixer.dist.php

      - name: Run test suite
        run: vendor/bin/phpunit --order-by=random --fail-on-incomplete --log-junit junit.xml --coverage-clover=clover.xml -d --min-coverage="min-coverage-rules.php"

      - name: Generate coverage report
        uses: clearlyip/code-coverage-report-action@v6
        id: code_coverage_report_action
        with:
          filename: 'clover.xml'
          only_list_changed_files: true
          fail_on_negative_difference: true
          artifact_download_workflow_names: 'ci,cron'

      - name: Debug
        uses: raven-actions/debug@v1

#      - name: Add coverage PR comment
#        uses: marocchino/sticky-pull-request-comment@v2
#        if: github.repository == 'robiningelbrecht/statistics-for-strava' && steps.code_coverage_report_action.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
#        with:
#          recreate: false
#          path: code-coverage-results.md